Creating a Vector

In [1]:
import numpy as np 
vector_row = np.array([1,2,3])
vector_column = np.array([[1], [2], [3]])

In [2]:
vector_row

array([1, 2, 3])

In [3]:
vector_column

array([[1],
       [2],
       [3]])

Creating a Matrix

In [4]:
matrix = np.array([[1, 2], [1, 2], [1, 2]])

In [5]:
type(matrix)

numpy.ndarray

In [6]:
matrix_obj = np.mat([[1, 2], [1, 2], [1, 2]]) #the matrix data structure is not recommended

In [7]:
type(matrix_obj)

numpy.matrix

In [8]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [9]:
matrix_obj

matrix([[1, 2],
        [1, 2],
        [1, 2]])

Creating a Sparse Matrix

In [10]:
from scipy import sparse

matrix  = np.array([[0, 0],
                   [0, 1], 
                   [3, 0]])

In [11]:
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [12]:
matrix_sparse = sparse.csr_matrix(matrix) # Sparse matrices
                                          #  only store nonzero elements and assume all other values will be zero

In [13]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [15]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [16]:
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [18]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [19]:
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


Pre-allocating Numpy arrays

In [20]:
vector = np.zeros(shape=5)

In [21]:
print(vector)

[0. 0. 0. 0. 0.]


In [25]:
matrix = np.full(shape=(3,3), fill_value=5)

In [26]:
print(matrix)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


Selecting Elements

In [27]:
vector = np.array([1, 2, 3, 4, 5, 6])

In [29]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [30]:
vector[2]

3

In [31]:
matrix[1, 1]

5

In [32]:
np.max(matrix)

9

In [33]:
np.max(matrix, axis=0)

array([7, 8, 9])

In [34]:
np.min(matrix, axis=1)

array([1, 4, 7])

Calculating the Average, Variace and Standar Deviation

In [35]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.mean(matrix)

5.0